# Generated by Django 2.2.6 on 2019-11-18 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img_url', models.ImageField(max_length=50, null=True, upload_to='')),
                ('text', models.TextField(null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(default='None', max_length=50)),
                ('img', models.FileField(max_length=50, null=True, upload_to='')),
                ('text', models.CharField(max_length=50, null=True)),
                ('locationX', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('locationY', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetarian_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vege_id', models.IntegerField(choices=[(1, '비건'), (2, '락토 베지테리언'), (3, '오보 베지테리언'), (4, '락토 오보 베지테리언'), (5, '페스코 베지테리언'), (6, '플로 베지테리언'), (7, '플렉시테리언'), (8, '해당사항없음')], default=8)),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Religion_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reli_id', models.IntegerField(choices=[(1, '힌두교'), (2, '불교'), (3, '기독교'), (4, '천주교'), (5, '이슬람교'), (6, '유대교'), (7, '시크교도'), (8, '무교')], default=8)),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationX', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('locationY', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('gender', models.IntegerField(choices=[(1, '남자'), (2, '여자')], default=1)),
                ('birth', models.DateTimeField()),
                ('reli_id', models.IntegerField(choices=[(1, '힌두교'), (2, '불교'), (3, '기독교'), (4, '천주교'), (5, '이슬람교'), (6, '유대교'), (7, '시크교도'), (8, '무교')], default=8)),
                ('vege_id', models.IntegerField(choices=[(1, '비건'), (2, '락토 베지테리언'), (3, '오보 베지테리언'), (4, '락토 오보 베지테리언'), (5, '페스코 베지테리언'), (6, '플로 베지테리언'), (7, '플렉시테리언'), (8, '해당사항없음')], default=8)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Menu')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hate_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hate_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
