# Generated by Django 2.2.6 on 2019-11-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTMT', '0002_auto_20191101_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reli_id',
            field=models.IntegerField(choices=[(1, '힌두교'), (2, '불교'), (3, '기독교'), (4, '천주교'), (5, '이슬람교'), (6, '유대교'), (7, '시크교도'), (8, '무교')]),
        ),
    ]
