# Generated by Django 2.2.6 on 2019-11-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTMT', '0003_auto_20191103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reli_id',
            field=models.IntegerField(choices=[(1, '힌두교'), (2, '불교'), (3, '기독교'), (4, '천주교'), (5, '이슬람교'), (6, '유대교'), (7, '시크교도'), (8, '무교')], default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vege_id',
            field=models.IntegerField(choices=[(1, '비건'), (2, '락토 베지테리언'), (3, '오보 베지테리언'), (4, '락토 오보 베지테리언'), (5, '페스코 베지테리언'), (6, '플로 베지테리언'), (7, '플렉시테리언'), (8, '해당사항없음')], default=8),
        ),
    ]
