# Generated by Django 2.2.6 on 2019-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTMT', '0004_auto_20191106_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
