# Generated by Django 2.2.6 on 2019-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTMT', '0005_auto_20191106_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateTimeField(),
        ),
    ]
