# Generated by Django 2.2.6 on 2019-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTMT', '0007_history_menu2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
