# Generated by Django 2.2.6 on 2019-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTMT', '0008_auto_20191115_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
