# Generated by Django 2.2.6 on 2019-11-18 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YTMT', '0010_auto_20191115_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu2',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='ingre_id',
            new_name='ingre',
        ),
        migrations.RenameField(
            model_name='hate_ingredient',
            old_name='ingre_id',
            new_name='ingre',
        ),
        migrations.RenameField(
            model_name='hate_menu',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingre_id',
            new_name='ingre',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingre_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingre',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetarian',
            name='ingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient'),
        ),
        migrations.AddField(
            model_name='vegetarian',
            name='vege_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='religion',
            name='ingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTMT.Ingredient'),
        ),
        migrations.AddField(
            model_name='religion',
            name='reli_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
